# Разведочный анализ данных: Data Cleaning. Практическая работа

## Цели практической работы
* Потренироваться выявлять и заполнять пропущенные значения в данных.
* Потренироваться преобразовывать типы данных.
* Потренироваться выявлять и обрабатывать аномальные значения в данных.
* Подготовить датафрейм к этапу генерации признаков.

## Задача

В этой практической работе вы продолжите исследовать и готовить данные для этапа моделирования: заполнять пропущенные значения в некоторых переменных, изменять типы данных и обрабатывать выбросы.

Напомним, что вы работаете с небольшой выборкой из коллекции подержанных автомобилей, выставленных на продажу в Соединённых Штатах. На этих данных вы построите первую модель классификации, определяющую категорию цены подержанного автомобиля в зависимости от характеристик транспортного средства.

## Описание датасета:
- `id`: идентификатор записи;
- `url`: URL записи о продаже;
- `region`: регион;
- `region_url`: URL региона;
- `price`: стоимость;
- `year`: год выпуска;
- `manufacturer`: производитель;
- `model`: модель;
- `condition`: состояние;
- `cylinders`: количество цилиндров;
- `fuel`: тип топлива;
- `odometer`: количество пройденных миль;
- `title_status`: статус;
- `transmission`: коробка передач;
- `VIN`: идентификационный номер;
- `drive`: тип привода;
- `size`: размер;
- `type`: кузов;
- `paint_color`: цвет;
- `image_url`: URL изображения;
- `description`: указанное описание;
- `county`: страна;
- `state`: штат;
- `lat`: широта;
- `long`: долгота;
- `posting_date`: дата размещения объявления о продаже;
- `price_category`: категория цены.

## Что входит в практическую работу
1. Загрузить датасет и ознакомиться с ним.
2. Исследовать переменные датасета на наличие пропусков.
3. Обработать пропуски в зависимости от типа переменной.
4. Изменить типы данных.
5. Исследовать данные на аномальные значения и скорректировать выбросы.

## Что оценивается
- Программа выдаёт верный ответ на заданном наборе данных.
- Описаны причины выбранного решения, если требуется.
- Код читабелен: переменным даны осмысленные названия, отступы и правила расстановки пробелов соблюдены.
- Репозиторий проекта содержит осмысленные коммиты с конкретными реализованными фичами, ветки названы согласно назначению, лишние файлы не хранятся в репозитории.
- В репозитории проекта соблюдена иерархия директорий согласно списку модулей и содержащихся в них видеоматериалов.
- Репозиторий проекта содержит файлы с данными, полученными в результате выполнения практической работы.

## Как отправить работу на проверку
Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

## Обязательные задачи

In [134]:
import pandas as pd

### Задача 1. Загрузка датасета и ознакомление с количеством пропущенных значений

1. Загрузите датасет из `data/df_out.csv` и выведите первые пять записей.

In [2]:
df = pd.read_csv('data/df_out.csv')
df.head(5)

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,2021-05-03 22:32:06+00:00

2. Выведите информацию о датафрейме и обратите внимание на оставшиеся незаполненные значения.

In [3]:
df.shape

(9902, 20)

In [4]:
df.describe(include = 'all')

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
count,9.902000e+03,9902,9902,9902,9.902000e+03,9868.000000,9902,9776,9841,9902.000000,9738,9902,9902,9902,9902,9902.000000,9902.000000,9902,9902,9902
unique,NaN,9902,393,405,NaN,NaN,40,3457,5,NaN,6,3,8999,9749,51,NaN,NaN,9862,3,9816
top,NaN,https://chattanooga.craigslist.org/ctd/d/chatt...,"kansas city, MO",https://kansascity.craigslist.org,NaN,NaN,ford,f-150,gas,NaN,clean,automatic,https://images.craigslist.org/00N0N_1xMPvfxRAI...,PLEASE VIEW THE FREE CARFAX HISTORY REPORT AT ...,ca,NaN,NaN,2021-05-03T13:23:38-0700,high,2021-04-22 15:01:24+00:00
freq,NaN,1,86,86,NaN,NaN,1626,148,8321,NaN,9423,7610,188,7,1108,NaN,NaN,2,3460,3
mean,7.311556e+09,NaN,NaN,NaN,2.068420e+04,2010.909708,NaN,NaN,NaN,93385.043123,NaN,NaN,NaN,NaN,NaN,38.594142,-94.165877,NaN,NaN,NaN
std,4.361977e+06,NaN,NaN,NaN,1.252344e+05,9.705988,NaN,NaN,NaN,63337.141614,NaN,NaN,NaN,NaN,NaN,5.844895,18.128504,NaN,NaN,NaN
min,7.301586e+09,NaN,NaN,NaN,5.000000e+02,1915.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,-67.144243,-158.069300,NaN,NaN,NaN
25%,7.308184e+09,NaN,NaN,NaN,7.880000e+03,2008.000000,NaN,NaN,NaN,39003.250000,NaN,NaN,NaN,NaN,NaN,34.830368,-110.322086,NaN,NaN,NaN
50%,7.312775e+09,NaN,NaN,NaN,1.559250e+04,2013.000000,NaN,NaN,NaN,89000.000000,NaN,NaN,NaN,NaN,NaN,39.298522,-88.000050,NaN,NaN,NaN
75%,7.315285e+09,NaN,NaN,NaN,2.799000e+04,2017.000000,NaN,NaN,NaN,137000.000000,NaN,NaN,NaN,NaN,NaN,42.428070,-80.830000,NaN,NaN,NaN
max,7.317090e+09,NaN,NaN,NaN,1.234568e+07,2022.000000,NaN,NaN,NaN,283995.000000,NaN,NaN,NaN,NaN,NaN,64.947500,173.885502,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9902 entries, 0 to 9901
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9902 non-null   int64
 1   url             9902 non-null   object
 2   region          9902 non-null   object
 3   region_url      9902 non-null   object
 4   price           9902 non-null   int64
 5   year            9868 non-null   float64
 6   manufacturer    9902 non-null   object
 7   model           9776 non-null   object
 8   fuel            9841 non-null   object
 9   odometer        9902 non-null   int64
 10  title_status    9738 non-null   object
 11  transmission    9902 non-null   object
 12  image_url       9902 non-null   object
 13  description     9902 non-null   object
 14  state           9902 non-null   object
 15  lat             9902 non-null   float64
 16  long            9902 non-null   float64
 17  posting_date    9902 non-null   object
 18  price_category  9902 non-null   object
 19  date            9902 non-null   object
dtypes: float64(3), int64(3), object(14)
memory usage: 1.5+ MB

3. Выведите количество полностью заполненных объектов и их процент из всей выборки. Воспользуйтесь материалами из видео.

In [6]:
print (f'Количество полностью заполненных объектов {len(df.dropna())}')
print (f'Процент полностью заполненных объектов от всей выборки {round(len(df.dropna()) / len(df) * 100, 2)}')

Количество полностью заполненных объектов 9543
Процент полностью заполненных объектов от всей выборки 96.37

4. Сохраните в переменную и выведите процент пропущенных значений для каждого признака, отсортируйте признаки по убыванию процента пропущенных значений. Воспользуйтесь материалами из видео и не забудьте передать верный параметр сортировки.

In [7]:
def missing_values(df):
    return round((df.isna().sum() / len(df)) * 100, 2).sort_values(ascending=False)

In [8]:
missing_values(df)

title_status      1.66
model             1.27
fuel              0.62
year              0.34
image_url         0.00
price_category    0.00
posting_date      0.00
long              0.00
lat               0.00
state             0.00
description       0.00
id                0.00
transmission      0.00
url               0.00
odometer          0.00
manufacturer      0.00
price             0.00
region_url        0.00
region            0.00
date              0.00
dtype: float64

5. Выведите список всех признаков, в которых имеются пропущенные значения. Воспользуйтесь результатом вывода предыдущего задания, чтобы отсортировать признаки, подходящие под условие.

In [9]:
mask_1 = missing_values(df)
missing_columns = mask_1[mask_1.values > 0].index.tolist()
missing_columns

['title_status', 'model', 'fuel', 'year']

### Задача 2. Обработка пропусков в годе выпуска автомобиля

1. Выведите количество значений для года выпуска автомобиля, включая пропущенные значения.

In [10]:
df.year.value_counts(dropna=False)

2017.0    808
2018.0    799
2016.0    733
2013.0    685
2015.0    664
         ...
1927.0      1
1958.0      1
1941.0      1
1935.0      1
1954.0      1
Name: year, Length: 90, dtype: int64

2. Выведите количество пропущенных значений в годе выпуска автомобиля.

In [11]:
df.year.isna().sum()

34

3. Выведите описательные статистики для года выпуска автомобиля.

In [12]:
df.year.describe()

count    9868.000000
mean     2010.909708
std         9.705988
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

4. Выведите записи, в которых год выпуска автомобиля не заполнен. Посмотрите на данные и подумайте, какую стратегию обработки значений можно применить.

In [13]:
df[df.year.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
342,7304102133,https://wenatchee.craigslist.org/ctd/d/wenatch...,wenatchee,https://wenatchee.craigslist.org,35880,NaN,other,500,gas,13508,clean,automatic,https://images.craigslist.org/00J0J_6IMoEUzIIM...,2019 *Ram* *1500* Big Horn/Lone Star 4x2 Quad ...,wa,47.434493,-120.320759,2021-04-09T06:31:03-0700,high,2021-04-09 13:31:03+00:00
418,7316337069,https://lasvegas.craigslist.org/ctd/d/scottsda...,las vegas,https://lasvegas.craigslist.org,84995,NaN,other,Super Duty F-350 SRW,diesel,1268,clean,automatic,https://images.craigslist.org/00x0x_iQCC0Ef28S...,2020 *Ford* *Super Duty F-350 SRW* 1K MILES. B...,nv,33.458277,-111.925970,2021-05-03T11:31:39-0700,high,2021-05-03 18:31:39+00:00
423,7315662117,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,43900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00f0f_7AwipNocNH...,"2019 *Dodge* *Grand Caravan* SE - $43,900Call ...",co,39.674406,-104.998604,2021-05-02T01:11:33-0600,high,2021-05-02 07:11:33+00:00
697,7316199009,https://nashville.craigslist.org/ctd/d/nashvil...,nashville,https://nashville.craigslist.org,28498,NaN,other,olet Silverado 1500,NaN,59246,NaN,automatic,https://images.craigslist.org/00T0T_dZ7nOXskCS...,2019 *Chevrolet* *Silverado 1500* 2019 CHEVROL...,tn,36.138022,-86.732261,2021-05-03T10:00:40-0500,high,2021-05-03 15:00:40+00:00
887,7316840794,https://denver.craigslist.org/ctd/d/american-f...,denver,https://denver.craigslist.org,60900,NaN,other,F-150,gas,6110,clean,automatic,https://images.craigslist.org/01616_bpzSdSRTbx...,"2020 *Ford* *F-150* PLATINUM FX4 Truck - $60,9...",co,40.362248,-111.785947,2021-05-04T12:11:22-0600,high,2021-05-04 18:11:22+00:00
900,7311915616,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,67900,NaN,other,Odyssey,gas,21,clean,automatic,https://images.craigslist.org/00404_erlbeKWEkn...,2020 *Honda* *Odyssey* EX-L w/Navi/RES Automat...,co,39.674406,-104.998604,2021-04-24T10:41:06-0600,high,2021-04-24 16:41:06+00:00
998,7306735187,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,38900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00F0F_3T6FM0XMZW...,"2019 *Dodge* *Grand Caravan* SE - $38,900Call ...",co,39.674406,-104.998604,2021-04-14T10:51:36-0600,high,2021-04-14 16:51:36+00:00
1208,7309954650,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,24975,NaN,other,CR-V,gas,44128,clean,automatic,https://images.craigslist.org/00000_2TUtAgLlCR...,"2019 *Honda* *CR-V* EX 2WD SUV - $24,975Call o...",fl,29.676827,-82.319202,2021-04-20T14:46:55-0400,high,2021-04-20 18:46:55+00:00
1308,7313865045,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,47900,NaN,other,a Sienna,gas,43701,clean,automatic,https://images.craigslist.org/00o0o_8XYp4Zygdj...,2018 *Toyota* *Sienna* LE Automatic Access Sea...,co,39.674406,-104.998604,2021-04-28T10:12:14-0600,high,2021-04-28 16:12:14+00:00
1828,7303344554,https://daytona.craigslist.org/ctd/d/new-smyrn...,daytona beach,https://daytona.craigslist.org,35850,NaN,other,Transit Cargo Van,gas,567,clean,automatic,https://images.craigslist.org/00a0a_d4XVrHnlxl...,"2020 *Ford* *Transit Cargo Van* T-250 148"" WB*...",fl,29.046240,-80.934561,2021-04-07T17:10:06-0400,high,2021-04-07 21:10:06+00:00
2270,7311762820,https://huntsville.craigslist.org/ctd/d/new-ca...,huntsville / decatur,https://huntsville.craigslist.org,29875,NaN,other,a Camry,gas,46947,clean,automatic,https://images.craigslist.org/01313_9nQ5n8dbnZ...,2019 *Toyota* *Camry* XSE Automatic Sedan - $2...,al,33.669601,-86.817617,2021-04-24T04:50:56-0500,high,2021-04-24 09:50:56+00:00
2481,7315662074,https://santafe.craigslist.org/ctd/d/denver-20...,santa fe / taos,https://santafe.craigslist.org,43900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00f0f_7AwipNocNH...,"2019 *Dodge* *Grand Caravan* SE - $43,900Call ...",nm,39.674406,-104.998604,2021-05-02T01:10:47-0600,high,2021-05-02 07:10:47+00:00
2603,7314588156,https://inlandempire.craigslist.org/ctd/d/hesp...,inland empire,https://inlandempire.craigslist.org,2599,NaN,other,olet Impala,other,1,clean,other,https://images.craigslist.org/00P0P_dKsEWbujM0...,Chevrolet Impala * AUCTION PRICES TO THE PUBL...,ca,34.451930,-117.287060,2021-04-29T16:19:54-0700,low,2021-04-29 23:19:54+00:00
2792,7310250813,https://omaha.craigslist.org/ctd/d/council-blu...,omaha / council bluffs,https://omaha.craigslist.org,28995,NaN,other,cadia,gas,3851,NaN,automatic,https://images.craigslist.org/00j0j_6hfE9qI1CV...,2019 *GMC* *Acadia* AWD 4dr SLT w/SLT-1 SUV - ...,ia,41.229172,-95.852118,2021-04-21T07:21:00-0500,high,2021-04-21 12:21:00+00:00
2931,7306678710,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,26975,NaN,other,n Maxima,gas,28367,clean,automatic,https://images.craigslist.org/01010_4uw9b06xiS...,2018 *Nissan* *Maxima* SR 3.5L Midnight Editio...,fl,29.676827,-82.319202,2021-04-14T11:25:14-0400,high,2021-04-14 15:25:14+00:00
3263,7316562384,https://honolulu.craigslist.org/oah/ctd/d/hono...,hawaii,https://honolulu.craigslist.org,37500,NaN,other,Grand Cherokee,NaN,26608,clean,automatic,https://images.craigslist.org/01111_h3zrI9JPSH...,2018 *Jeep* *Grand Cherokee* High Altitude 4x2...,hi,21.318059,-157.865187,2021-05-03T16:10:46-1000,high,2021-05-04 02:10:46+00:00
3476,7307209305,https://northmiss.craigslist.org/ctd/d/vicksbu...,north mississippi,https://northmiss.craigslist.org,64900,NaN,other,500,diesel,12338,NaN,automatic,https://images.craigslist.org/00E0E_hZTYK06AGo...,2020 *Ram* *3500* RAM 3500 DUALLY 4X4 CUMMINS ...,ms,32.332046,-90.857163,2021-04-15T10:45:56-0500,high,2021-04-15 15:45:56+00:00
3488,7304711487,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,67900,NaN,other,Odyssey,gas,21,clean,automatic,https://images.craigslist.org/00404_erlbeKWEkn...,2020 *Honda* *Odyssey* EX-L w/Navi/RES Automat...,co,39.674406,-104.998604,2021-04-10T10:12:15-0600,high,2021-04-10 16:12:15+00:00
3634,7309869204,https://scottsbluff.craigslist.org/ctd/d/denve...,scottsbluff / panhandle,https://scottsbluff.craigslist.org,48900,NaN,other,Grand Caravan,NaN,19,clean,automatic,https://images.craigslist.org/00V0V_72KAx8GRuN...,2019 *Dodge* *Grand Caravan* SE Plus Wagon - $...,ne,39.674406,-104.998604,2021-04-20T10:41:16-0600,high,2021-04-20 16:41:16+00:00
4178,7304693422,https://shreveport.craigslist.org/ctd/d/vicksb...,shreveport,https://shreveport.craigslist.org,53700,NaN,other,ierra 1500,gas,35676,NaN,automatic,https://images.craigslist.org/00O0O_cpIkn2jwHN...,2020 *GMC* *Sierra 1500* SIERRA 1500 AT4 4X4 5...,la,32.332046,-90.857163,2021-04-10T10:44:02-0500,high,2021-04-10 15:44:02+00:00
6055,7310371320,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,49900,NaN,other,Enclave,gas,10345,clean,automatic,https://images.craigslist.org/00M0M_sPt1lwAVRY...,2018 *Buick* *Enclave* FWD 4dr Essence SUV - $...,co,39.674406,-104.998604,2021-04-21T10:12:30-0600,high,2021-04-21 16:12:30+00:00
6130,7309904568,https://omaha.craigslist.org/ctd/d/omaha-2020-...,omaha / council bluffs,https://omaha.craigslist.org,25399,NaN,other,Envision,NaN,8492,rebuilt,automatic,https://images.craigslist.org/01515_geiPTG1MZG...,2020 *Buick* *Envision* AWD 4dr Essence SUV - ...,ia,41.207382,-96.023096,2021-04-20T12:31:36-0500,high,2021-04-20 17:31:36+00:00
6254,7315207437,https://huntsville.craigslist.org/ctd/d/new-ca...,huntsville / decatur,https://huntsville.craigslist.org,35495,NaN,other,Series,gas,14000,clean,automatic,https://images.craigslist.org/01212_85QVVsEWjT...,"2020 *BMW* *3 Series* 330i Sedan - $35,495Call...",al,33.669601,-86.817617,2021-05-01T04:50:32-0500,high,2021-05-01 09:50:32+00:00
7122,7310924082,https://omaha.craigslist.org/ctd/d/omaha-2018-...,omaha / council bluffs,https://omaha.craigslist.org,12995,NaN,other,u Impreza,gas,16740,rebuilt,automatic,https://images.craigslist.org/01212_dEfENLNXWW...,2018 *Subaru* *Impreza* 2.0i 4-door CVT Sedan ...,ia,41.207382,-96.023096,2021-04-22T12:20:37-0500,medium,2021-04-22 17:20:37+00:00
7567,7316247218,https://lasvegas.craigslist.org/ctd/d/scottsda...,las vegas,https://lasvegas.craigslist.org,69995,NaN,other,F-150,gas,412,clean,automatic,https://images.craigslist.org/00n0n_kNzqmJoY2a...,2021 *Ford* *F-150* NEW 2021 FORD F150 SUPERCR...,nv,33.458277,-111.925970,2021-05-03T09:15:32-0700,high,2021-05-03 16:15:32+00:00
7730,7314898718,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,38975,NaN,other,500,gas,28689,clean,automatic,https://images.craigslist.org/00e0e_3SqmUoLwUf...,2019 *Ram* *2500* Tradesman 4x2 Crew Cab 8' Bo...,fl,29.676827,-82.319202,2021-04-30T13:32:48-0400,high,2021-04-30 17:32:48+00:00
7734,7314454466,https://billings.craigslist.org/ctd/d/denver-2...,billings,https://billings.craigslist.org,49900,NaN,other,a Sienna,gas,34294,clean,automatic,https://images.craigslist.org/00707_lMMxHyLoAR...,2019 *Toyota* *Sienna* LE Automatic Access Sea...,mt,39.674406,-104.998604,2021-04-29T13:00:48-0600,high,2021-04-29 19:00:48+00:00
8437,7310829676,https://tucson.craigslist.org/ctd/d/tempe-2020...,tucson,https://tucson.craigslist.org,83877,NaN,other,ierra 2500HD,diesel,25363,NaN,automatic,https://images.craigslist.org/00A0A_nd5C1ILCvJ...,2020 *GMC* *Sierra 2500HD* LIFTED - AT4 Editio...,az,33.437098,-111.925724,2021-04-22T07:50:52-0700,high,2021-04-22 14:50:52+00:00
8714,7316852999,https://memphis.craigslist.org/ctd/d/memphis-2...,memphis,https://memphis.craigslist.org,19979,NaN,other,CX-5,gas,17183,clean,automatic,https://images.craigslist.org/00x0x_1sp7mb28W4...,"2019 *Mazda* *CX-5* Sport FWD SUV - $19,979Cal...",tn,35.191437,-89.894973,2021-05-04T13:30:34-0500,medium,2021-05-04 18:30:34+00:00
9237,7316270709,https://denver.craigslist.org/ctd/d/denver-201...,denver,https://denver.craigslist.org,49900,NaN,other,a Sienna,gas,34294,clean,automatic,https://images.craigslist.org/00707_lMMxHyLoAR...,2019 *Toyota* *Sienna* LE Automatic Access Sea...,co,39.674406,-104.998604,2021-05-03T10:50:33-0600,high,2021-05-03 16:50:33+00:00
9454,7312938642,https://lasvegas.craigslist.org/ctd/d/scottsda...,las vegas,https://lasvegas.craigslist.org,67995,NaN,other,olet Silverado 1500,gas,7511,clean,automatic,https://images.craigslist.org/00M0M_74pDndl5gQ...,2020 *Chevrolet* *Silverado 1500* 6.2L HIGH CO...,nv,33.458277,-111.925970,2021-04-26T11:30:40-0700,high,2021-04-26 18:30:40+00:00
9626,7309216259,https://omaha.craigslist.org/ctd/d/omaha-2019-...,omaha / council bluffs,https://omaha.craigslist.org,29995,NaN,other,Enclave,gas,1036,rebuilt,automatic,https://images.craigslist.org/01010_1PAwiL9HwM...,2019 *Buick* *Enclave* AWD 4dr Essence SUV - $...,ia,41.207382,-96.023096,2021-04-19T09:30:41-0500,high,2021-04-19 14:30:41+00:00
9752,7316246632,https://sanantonio.craigslist.org/ctd/d/scotts...,san antonio,https://sanantonio.craigslist.org,49995,NaN,other,500,gas,19078,clean,automatic,https://images.craigslist.org/00p0p_lva0tqTnF1...,2019 *Ram* *1500* LIFTED 2019 RAM 1500 WITH BU...,tx,33.458277,-111.925970,2021-05-03T11:14:44-0500,high,2021-05-03 16:14:44+00:00
9855,7314033574,https://inlandempire.craigslist.org/ctd/d/scot...,inland empire,https://inlandempire.craigslist.org,54995,NaN,other,F-150,gas,180,clean,automatic,https://images.craigslist.org/00d0d_92wTNhRT7B...,2020 *Ford* *F-150* 180 MILES. LIFTED FORD F15...,ca,33.458277,-111.925970,2021-04-28T13:51:27-0700,high,2021-04-28 20:51:27+00:00

5. Обработайте пропуски, удалив записи, в которых год выпуска автомобиля не заполнен, и сохраните обновлённый датафрейм, а затем выведите его размерность.

In [14]:
df = df[df.year.notna()]
df.shape

(9868, 20)

6. Выведите количество пропущенных значений в годе выпуска автомобиля для обновлённого датафрейма.

In [15]:
print("Количество пропущенных значений в year:", len(df[df.year.isna()]))

Количество пропущенных значений в year: 0

### Задача 3. Обработка пропусков в типе топлива

1. Выведите количество значений для типа топлива, включая пропущенные значения. Обратите внимание на количество пропущенных значений.

In [16]:
df.fuel.value_counts(dropna=False)

gas         8298
other        725
diesel       643
hybrid       104
NaN           54
electric      44
Name: fuel, dtype: int64

2. Выведите описательные статистики для типа топлива.

In [17]:
df.fuel.describe()

count     9814
unique       5
top        gas
freq      8298
Name: fuel, dtype: object

3. Выведите записи, в которых тип топлива не заполнен. Посмотрите на данные и подумайте, какую стратегию обработки значений можно применить.

In [18]:
df[df.fuel.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
32,7309910590,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,4977,2001.0,toyota,camry solara 2dr cpe se v6 auto (natl),NaN,193242,clean,automatic,https://images.craigslist.org/00F0F_ebtJlxCQjv...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-20T10:40:15-0700,low,2021-04-20 17:40:15+00:00
78,7314559074,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,27977,2009.0,ford,"f-150 4wd supercrew 145"" platinum",NaN,79522,clean,automatic,https://images.craigslist.org/00L0L_khoMmqXaSJ...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-29T15:15:30-0700,high,2021-04-29 22:15:30+00:00
273,7315141987,https://honolulu.craigslist.org/oah/ctd/d/fort...,hawaii,https://honolulu.craigslist.org,29888,2019.0,nissan,frontier crew cab 4x2 sv auto,NaN,10679,clean,automatic,https://images.craigslist.org/00F0F_d9wEXQuSyu...,***Call Us for more information at: 877-262-34...,hi,21.344376,-157.896975,2021-04-30T15:50:19-1000,high,2021-05-01 01:50:19+00:00
469,7316807613,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,13436,2006.0,chevrolet,"silverado 1500 ext cab 143.5"" wb 4wd ls",NaN,172700,clean,automatic,https://images.craigslist.org/00l0l_35tV0gQdD8...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-05-04T10:20:19-0700,medium,2021-05-04 17:20:19+00:00
1002,7314561306,https://cnj.craigslist.org/ctd/d/parlin-2000-c...,central NJ,https://cnj.craigslist.org,5894,2000.0,chevrolet,"s-10 ext cab 123"" wb ls",NaN,78740,clean,automatic,https://images.craigslist.org/00O0O_8vd70bT1rY...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-29T18:20:19-0400,low,2021-04-29 22:20:19+00:00
1269,7310297136,https://westernmass.craigslist.org/ctd/d/johns...,western massachusetts,https://westernmass.craigslist.org,6000,2008.0,other,IC IC,NaN,0,NaN,automatic,https://images.craigslist.org/00404_cBFpBKbfr2...,"2008 *IC* *IC* CE300 - $6,000Call Us Today! 85...",ma,43.008105,-74.352011,2021-04-21T10:11:05-0400,low,2021-04-21 14:11:05+00:00
1307,7310414739,https://nwct.craigslist.org/ctd/d/melville-200...,northwest CT,https://nwct.craigslist.org,11995,2007.0,gmc,c-7500 multiple uses perfect,NaN,50098,clean,automatic,https://images.craigslist.org/00T0T_jvsOAKSGAr...,2007 *GMC* *C-7500 MULTIPLE USES PERFECT* FOR ...,ct,40.681179,-73.430488,2021-04-21T13:18:41-0400,medium,2021-04-21 17:18:41+00:00
1670,7316342709,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,19942,2017.0,ram,"promaster cargo van 1500 low roof 118"" wb",NaN,88836,clean,automatic,https://images.craigslist.org/00707_6ZlIIpYmGf...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T14:40:24-0400,medium,2021-05-03 18:40:24+00:00
1830,7315151536,https://honolulu.craigslist.org/oah/ctd/d/fort...,hawaii,https://honolulu.craigslist.org,29988,2019.0,toyota,sienna le fwd 8-passenger (natl),NaN,18762,clean,automatic,https://images.craigslist.org/00R0R_dO0gtiRwLa...,***Call Us for more information at: 877-262-34...,hi,21.344376,-157.896975,2021-04-30T16:25:22-1000,high,2021-05-01 02:25:22+00:00
1953,7316383024,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,10742,2016.0,volkswagen,passat 4dr sdn 1.8t auto r-line pzev,NaN,54477,clean,automatic,https://images.craigslist.org/00f0f_7yS2mCosQE...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:45:18-0400,medium,2021-05-03 19:45:18+00:00
2015,7314304193,https://sanantonio.craigslist.org/ctd/d/san-an...,san antonio,https://sanantonio.craigslist.org,16995,2018.0,mitsubishi,outlander sport es 2.0 cvt,NaN,25655,clean,automatic,https://images.craigslist.org/00D0D_gChRpTglWZ...,2018 Mitsubishi Outlander Sport ES 2.0 CVT ...,tx,29.529409,-98.496166,2021-04-29T09:45:30-0500,medium,2021-04-29 14:45:30+00:00
2109,7302733118,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,14700,2016.0,ford,fusion,NaN,95674,NaN,other,https://images.craigslist.org/00O0O_fkFRDDi4yq...,Car Starz Call Sales at 717-401-4221 2016 Ford...,pa,41.261540,-78.704520,2021-04-06T14:39:29-0400,medium,2021-04-06 18:39:29+00:00
2344,7314161453,https://honolulu.craigslist.org/oah/ctd/d/hono...,hawaii,https://honolulu.craigslist.org,18000,2017.0,dodge,journey,NaN,30273,clean,automatic,https://images.craigslist.org/00404_aEGhCFEEz3...,"2017 *Dodge* *Journey* SXT FWD SUV - $18,000Ca...",hi,21.318059,-157.865187,2021-04-28T16:00:34-1000,medium,2021-04-29 02:00:34+00:00
2684,7309203638,https://wenatchee.craigslist.org/ctd/d/wenatch...,wenatchee,https://wenatchee.craigslist.org,32880,2017.0,ford,f-150,NaN,70927,clean,automatic,https://images.craigslist.org/00404_82ntZ72mES...,"2017 *Ford* *F-150* XLT Truck - $32,880Call or...",wa,47.434493,-120.320759,2021-04-19T07:10:47-0700,high,2021-04-19 14:10:47+00:00
2779,7315330404,https://washingtondc.craigslist.org/nva/ctd/d/...,"washington, DC",https://washingtondc.craigslist.org,16995,2012.0,cadillac,escalade awd 4dr luxury,NaN,153932,clean,automatic,https://images.craigslist.org/00101_ks8k5Dx5M2...,2012 Cadillac Escalade AWD 4dr Luxury C...,dc,38.884033,-77.097657,2021-05-01T12:01:27-0400,medium,2021-05-01 16:01:27+00:00
2813,7313525045,https://cnj.craigslist.org/ctd/d/parlin-2019-n...,central NJ,https://cnj.craigslist.org,15887,2019.0,nissan,altima 2.5 s sedan,NaN,42683,clean,automatic,https://images.craigslist.org/01616_3tegH6j52E...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-27T16:35:24-0400,medium,2021-04-27 20:35:24+00:00
2868,7310562680,https://newjersey.craigslist.org/ctd/d/parlin-...,north jersey,https://newjersey.craigslist.org,23717,2018.0,alfa-romeo,romeo stelvio awd,NaN,55645,clean,automatic,https://images.craigslist.org/01111_euhp0VXlye...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-21T17:25:32-0400,high,2021-04-21 21:25:32+00:00
2909,7309460386,https://cincinnati.craigslist.org/ctd/d/camp-d...,cincinnati,https://cincinnati.craigslist.org,9995,2014.0,chevrolet,cruze 4dr sdn auto 1lt,NaN,80859,clean,automatic,https://images.craigslist.org/00606_boG5lumdt0...,***Call Us for more information at: 513-453-41...,oh,39.171991,-84.271999,2021-04-19T16:20:13-0400,medium,2021-04-19 20:20:13+00:00
2947,7314857030,https://westslope.craigslist.org/ctd/d/grand-j...,western slope,https://westslope.craigslist.org,9493,2013.0,honda,civic sdn 4dr auto lx,NaN,140793,clean,automatic,https://images.craigslist.org/00X0X_3CTPHZ93GI...,***Call Us for more information at: 855-975-45...,co,39.081944,-108.588542,2021-04-30T10:25:28-0600,low,2021-04-30 16:25:28+00:00
3075,7314544641,https://cnj.craigslist.org/ctd/d/parlin-2017-d...,central NJ,https://cnj.craigslist.org,15000,2017.0,dodge,grand caravan se wagon,NaN,29982,clean,automatic,https://images.craigslist.org/00X0X_dbn3lTfaSy...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-29T17:45:45-0400,medium,2021-04-29 21:45:45+00:00
3186,7304158723,https://bham.craigslist.org/ctd/d/new-castle-2...,birmingham,https://bham.craigslist.org,26500,2014.0,gmc,sierra 1500,NaN,162934,clean,automatic,https://images.craigslist.org/00a0a_j5GjqgsLVW...,"2014 *GMC* *Sierra 1500* 4WD Crew Cab 143.5"" S...",al,33.669601,-86.817617,2021-04-09T10:11:24-0500,high,2021-04-09 15:11:24+00:00
3197,7309551647,https://westslope.craigslist.org/ctd/d/grand-j...,western slope,https://westslope.craigslist.org,18499,2016.0,jeep,renegade 4wd 4dr trailhawk,NaN,75314,clean,automatic,https://images.craigslist.org/00W0W_5sXgFdHJO9...,***Call Us for more information at: 855-975-45...,co,39.081944,-108.588542,2021-04-19T17:05:21-0600,medium,2021-04-19 23:05:21+00:00
3347,7304419189,https://cincinnati.craigslist.org/ctd/d/camp-d...,cincinnati,https://cincinnati.craigslist.org,9700,2011.0,toyota,corolla 4dr sdn auto s (natl),NaN,126872,clean,automatic,https://images.craigslist.org/00y0y_kSkbjQHfGP...,***Call Us for more information at: 513-453-41...,oh,39.171991,-84.271999,2021-04-09T18:15:24-0400,medium,2021-04-09 22:15:24+00:00
3654,7310520763,https://westslope.craigslist.org/ctd/d/grand-j...,western slope,https://westslope.craigslist.org,2450,2005.0,infiniti,g35 sedan g35 4dr sdn auto,NaN,140782,clean,automatic,https://images.craigslist.org/00g0g_4Ljc5MYi8r...,***Call Us for more information at: 855-975-45...,co,39.081944,-108.588542,2021-04-21T14:10:26-0600,low,2021-04-21 20:10:26+00:00
3717,7308856751,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,26900,2006.0,ram,2500 4dr quad cab 160.5 4wd slt,NaN,177001,clean,manual,https://images.craigslist.org/00Y0Y_vNEe5hSHH9...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-18T11:35:16-0700,high,2021-04-18 18:35:16+00:00
3777,7314143519,https://boise.craigslist.org/ctd/d/nampa-1971-...,boise,https://boise.craigslist.org,10395,1971.0,other,American LaFrance Fire Truck,NaN,78974,clean,other,https://images.craigslist.org/00909_aLVPntLOWj...,"1971 American LaFrance Fire Truck - $10,395....",id,43.593700,-116.536000,2021-04-28T19:02:38-0600,medium,2021-04-29 01:02:38+00:00
3797,7311269192,https://omaha.craigslist.org/ctd/d/council-blu...,omaha / council bluffs,https://omaha.craigslist.org,9995,2016.0,ford,focus,NaN,38505,NaN,automatic,https://images.craigslist.org/00o0o_jpNzU8uGRA...,"2016 *Ford* *Focus* 4dr Sedan Titanium - $9,99...",ia,41.229172,-95.852118,2021-04-23T07:20:53-0500,medium,2021-04-23 12:20:53+00:00
4946,7311631527,https://nashville.craigslist.org/ctd/d/nashvil...,nashville,https://nashville.craigslist.org,12995,2014.0,jeep,cherokee,NaN,103028,NaN,automatic,https://images.craigslist.org/00x0x_hptQ5xMo66...,VIN: 1C4PJMAB1EW106979Year: 2014Make: JEEPMode...,tn,36.235220,-86.758300,2021-04-23T18:01:00-0500,medium,2021-04-23 23:01:00+00:00
5191,7312115428,https://eugene.craigslist.org/ctd/d/eugene-201...,eugene,https://eugene.craigslist.org,9828,2010.0,volkswagen,tiguan fwd 4dr sel,NaN,121515,clean,automatic,https://images.craigslist.org/00f0f_6z7FlCkp2G...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-24T15:30:11-0700,medium,2021-04-24 22:30:11+00:00
5206,7307388962,https://medford.craigslist.org/ctd/d/medford-2...,medford-ashland,https://medford.craigslist.org,14984,2010.0,ford,expedition,NaN,128975,NaN,other,https://images.craigslist.org/00B0B_aSYu1CvWOQ...,2010 Ford Expedition Eddie Bauer Sport Utility...,or,42.329925,-122.875811,2021-04-15T13:28:27-0700,medium,2021-04-15 20:28:27+00:00
5520,7314750640,https://syracuse.craigslist.org/ctd/d/johnstow...,syracuse,https://syracuse.craigslist.org,5595,2011.0,gmc,starcraft,NaN,0,NaN,automatic,https://images.craigslist.org/00a0a_c2wkMhtR81...,"2011 *GMC* *STARCRAFT* QUEST DRW - $5,595Call ...",ny,43.008105,-74.352011,2021-04-30T09:11:31-0400,low,2021-04-30 13:11:31+00:00
5752,7314282600,https://washingtondc.craigslist.org/nva/ctd/d/...,"washington, DC",https://washingtondc.craigslist.org,18595,2015.0,honda,odyssey 5dr touring elite,NaN,107176,clean,automatic,https://images.craigslist.org/00r0r_6a7U1DBrVv...,2015 Honda Odyssey 5dr Touring Elite Ca...,dc,38.884033,-77.097657,2021-04-29T10:02:00-0400,medium,2021-04-29 14:02:00+00:00
5832,7310526453,https://westslope.craigslist.org/ctd/d/grand-j...,western slope,https://westslope.craigslist.org,1750,2003.0,nissan,xterra 4dr xe 2wd v6 auto,NaN,201570,clean,automatic,https://images.craigslist.org/00U0U_8aitnvaflm...,***Call Us for more information at: 855-975-45...,co,39.081944,-108.588542,2021-04-21T14:20:28-0600,low,2021-04-21 20:20:28+00:00
5888,7316686098,https://cnj.craigslist.org/ctd/d/hillside-2019...,central NJ,https://cnj.craigslist.org,28900,2019.0,honda,cr-v ex-l awd,NaN,15392,clean,automatic,https://images.craigslist.org/00707_YP0z08DLmH...,***Call Us for more information at: 973-354-52...,nj,40.697349,-74.219903,2021-05-04T10:01:53-0400,high,2021-05-04 14:01:53+00:00
5997,7310551940,https://cincinnati.craigslist.org/ctd/d/camp-d...,cincinnati,https://cincinnati.craigslist.org,58500,2019.0,chevrolet,"silverado 2500hd 4wd crew cab 153.7"" ltz",NaN,50930,clean,automatic,https://images.craigslist.org/01010_ldls5xr3zz...,***Call Us for more information at: 513-453-41...,oh,39.171991,-84.271999,2021-04-21T17:05:31-0400,high,2021-04-21 21:05:31+00:00
6076,7314719321,https://kpr.craigslist.org/ctd/d/yakima-2020-n...,kennewick-pasco-richland,https://kpr.craigslist.org,16999,2020.0,nissan,versa sv,NaN,24140,NaN,other,https://images.craigslist.org/01313_kxS9Hqa3vo...,"2020 Nissan Versa SV - $16,999 \tOne Stop \t17...",wa,46.585652,-120.478580,2021-04-30T04:13:41-0700,medium,2021-04-30 11:13:41+00:00
6096,7316456657,https://westslope.craigslist.org/ctd/d/grand-j...,western slope,https://westslope.craigslist.org,9788,2013.0,hyundai,sonata 4dr sdn 2.4l auto limited,NaN,117773,clean,automatic,https://images.craigslist.org/00h0h_i7XoHUvw0i...,***Call Us for more information at: 855-975-45...,co,39.081944,-108.588542,2021-05-03T15:55:22-0600,medium,2021-05-03 21:55:22+00:00
6106,7305971655,https://lancaster.craigslist.org/ctd/d/brockpo...,lancaster,https://lancaster.craigslist.org,7600,2012.0,jeep,patriot,NaN,95674,NaN,other,https://images.craigslist.org/00909_hw8K8SHtsk...,Car Starz Call Sales at 717-401-4221 2012 Jeep...,pa,41.261540,-78.704520,2021-04-12T21:08:22-0400,low,2021-04-13 01:08:22+00:00
6235,7304094040,https://elpaso.craigslist.org/ctd/d/johnstown-...,el paso,https://elpaso.craigslist.org,8500,2010.0,other,INTERNATIONAL IC,NaN,134385,NaN,automatic,https://images.craigslist.org/00n0n_eGFH9KY70W...,"2010 *INTERNATIONAL* *IC* CE300 - $8,500Call U...",tx,43.008105,-74.352011,2021-04-09T07:12:52-0600,low,2021-04-09 13:12:52+00:00
6500,7314261064,https://omaha.craigslist.org/ctd/d/council-blu...,omaha / council bluffs,https://omaha.craigslist.org,13995,2016.0,ford,taurus,NaN,49020,NaN,automatic,https://images.craigslist.org/00L0L_hO1So9ovo1...,2016 *Ford* *Taurus* 4dr Sedan Limited AWD - $...,ia,41.229172,-95.852118,2021-04-29T08:12:45-0500,medium,2021-04-29 13:12:45+00:00
6554,7315111002,https://honolulu.craigslist.org/oah/ctd/d/fort...,hawaii,https://honolulu.craigslist.org,12900,2013.0,honda,civic sdn 4dr auto ex-l,NaN,68522,clean,automatic,https://images.craigslist.org/00e0e_5IiDyEzZOh...,***Call Us for more information at: 877-262-34...,hi,21.344376,-157.896975,2021-04-30T14:15:25-1000,medium,2021-05-01 00:15:25+00:00
6741,7310860252,https://charlotte.craigslist.org/ctd/d/greensb...,charlotte,https://charlotte.craigslist.org,6998,2008.0,honda,civic cpe,NaN,95674,NaN,other,https://images.craigslist.org/00l0l_3evmKC5YBJ...,2008 Honda Civic Cpe 2dr Auto EX-L Oak Ridge ...,nc,36.129540,-79.957520,2021-04-22T11:41:26-0400,low,2021-04-22 15:41:26+00:00
6845,7310766348,https://greensboro.craigslist.org/ctd/d/high-p...,greensboro,https://greensboro.craigslist.org,3999,2001.0,honda,civic,NaN,95674,NaN,other,https://images.craigslist.org/01212_hrL1gYZLbs...,Vann York Bargain Cars Call Sales at336-628-88...,nc,35.942696,-80.034679,2021-04-22T08:29:39-0400,low,2021-04-22 12:29:39+00:00
6890,7305911263,https://sarasota.craigslist.org/ctd/d/bradento...,sarasota-bradenton,https://sarasota.craigslist.org,7777,2014.0,chrysler,town & country,NaN,137312,clean,automatic,https://images.craigslist.org/00C0C_lj51oOvup7...,2014 *Chrysler* *Town & Country* 4dr Wagon Tou...,fl,27.473591,-82.570679,2021-04-12T18:43:37-0400,low,2021-04-12 22:43:37+00:00
7397,7313584978,https://cnj.craigslist.org/ctd/d/parlin-2019-h...,central NJ,https://cnj.craigslist.org,15886,2019.0,hyundai,elantra sel auto,NaN,8266,clean,automatic,https://images.craigslist.org/01717_fuY1H8n1EO...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-27T18:35:21-0400,medium,2021-04-27 22:35:21+00:00
7981,7310526393,https://newjersey.craigslist.org/ctd/d/parlin-...,north jersey,https://newjersey.craigslist.org,19787,2018.0,ford,edge sel awd,NaN,89484,clean,automatic,https://images.craigslist.org/00E0E_lXtpLTQwuT...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-21T16:20:20-0400,medium,2021-04-21 20:20:20+00:00
8181,7314112375,https://westslope.craigslist.org/ctd/d/grand-j...,western slope,https://westslope.craigslist.org,9995,2013.0,ford,fusion 4dr sdn se fwd,NaN,111576,clean,automatic,https://images.craigslist.org/00z0z_fFpkeQ8fzr...,***Call Us for more information at: 855-975-45...,co,39.081944,-108.588542,2021-04-28T17:40:29-0600,medium,2021-04-28 23:40:29+00:00
8218,7308149122,https://harrisburg.craigslist.org/ctd/d/sunbur...,harrisburg,https://harrisburg.craigslist.org,49995,2015.0,dodge,challenger hellcat 6-speed manual,NaN,4697,clean,manual,https://images.craigslist.org/00D0D_cjooG7lIJu...,2015 Dodge Challenger Hellcat 6-Speed Manual -...,pa,40.859162,-76.773484,2021-04-17T07:07:17-0400,high,2021-04-17 11:07:17+00:00
8682,7313576130,https://cnj.craigslist.org/ctd/d/parlin-2012-j...,central NJ,https://cnj.craigslist.org,23500,2012.0,jeep,wrangler unlimited 4wd 4dr sahara,NaN,105927,clean,automatic,https://images.craigslist.org/00u0u_erwAahcIeQ...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-27T18:15:18-0400,high,2021-04-27 22:15:18+00:00
9351,7309365699,https://fortmyers.craigslist.org/chl/ctd/d/bra...,ft myers / SW florida,https://fortmyers.craigslist.org,14997,2010.0,ford,e-350,NaN,153120,clean,manual,https://images.craigslist.org/00606_hQvq6K6D4p...,"2010 *Ford* *E-350* 12 Passenger Van - $14,997...",fl,27.479823,-82.571497,2021-04-19T14:01:14-0400,medium,2021-04-19 18:01:14+00:00
9541,7313475467,https://eugene.craigslist.org/ctd/d/eugene-201...,eugene,https://eugene.craigslist.org,9979,2012.0,chevrolet,equinox awd 4dr lt w/1lt,NaN,165554,clean,automatic,https://images.craigslist.org/00q0q_haS6HKqYq4...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-27T12:10:24-0700,medium,2021-04-27 19:10:24+00:00
9708,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,NaN,95674,NaN,other,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low,2021-04-28 18:25:32+00:00
9718,7314349617,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,11976,2008.0,acura,mdx 4wd 4dr,NaN,156801,clean,automatic,https://images.craigslist.org/00K0K_8iyrQ1sWEh...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-29T09:05:16-0700,medium,2021-04-29 16:05:16+00:00

4. Обработайте пропуски, заполнив незаполненные значения типа топлива значением `other`, и сохраните изменения. Обратите внимание, что мы заполняем пропуски не самым популярным значением в выборке.

In [19]:
df.fuel = df.fuel.fillna('other')

5. Выведите для обновлённого датафрейма количество пропущенных значений для типа топлива.

In [20]:
print("Количество пропущенных значений в fuel:", df.fuel.isna().sum())

Количество пропущенных значений в fuel: 0

### Задача 4. Обработка пропусков в модели автомобиля

1. Выведите количество значений для модели автомобиля, включая пропущенные значения. Обратите внимание на количество пропущенных значений.

In [21]:
df.model.value_counts(dropna=False)

f-150                        148
NaN                          126
silverado 1500               106
1500                         100
camry                         76
                            ...
sorrento lx v6                 1
sierra1500 crewcab 4x4         1
corolla se                     1
xc60 t6 inscription sport      1
a3 2.0t premium plus pzev      1
Name: model, Length: 3438, dtype: int64

2. Выведите описательные статистики для модели автомобиля.

In [22]:
df.model.describe()

count      9742
unique     3437
top       f-150
freq        148
Name: model, dtype: object

3. Выведите записи, в которых модель автомобиля не заполнена. Посмотрите на данные и подумайте, какую стратегию обработки значений можно применить.

In [23]:
df[df.model.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
67,7316913641,https://ventura.craigslist.org/cto/d/camarillo...,ventura county,https://ventura.craigslist.org,3000,2005.0,rover,NaN,gas,165206,clean,automatic,https://images.craigslist.org/00S0S_b3yx6L4N2S...,2005 Range Rover HSE Changed Oil and now engi...,ca,34.219565,-119.001986,2021-05-04T13:11:15-0700,low,2021-05-04 20:11:15+00:00
140,7316550853,https://chicago.craigslist.org/chc/cto/d/midlo...,chicago,https://chicago.craigslist.org,3000,2006.0,jeep,NaN,gas,132000,clean,automatic,https://images.craigslist.org/01111_kNv3EKjH4H...,SUPER CLEAN 2006 JEEP LIBEERY RANAGADE 4X4 O...,il,41.618957,-87.726334,2021-05-03T20:33:40-0500,low,2021-05-04 01:33:40+00:00
149,7303575863,https://worcester.craigslist.org/ctd/d/fitchbu...,worcester / central MA,https://worcester.craigslist.org,7800,2007.0,gmc,NaN,gas,190000,clean,automatic,https://images.craigslist.org/00f0f_iWjiToqea2...,2007 gmc with plow leather loaded nice truck r...,ma,42.579600,-71.803100,2021-04-08T09:10:07-0400,low,2021-04-08 13:10:07+00:00
198,7315267860,https://gainesville.craigslist.org/ctd/d/kissi...,gainesville,https://gainesville.craigslist.org,19200,2012.0,ram,NaN,gas,121371,clean,automatic,https://images.craigslist.org/00W0W_hHV4D0Po0G...,2012 RAM 1500 Laramie Crew Cab 2WD Offered...,fl,28.329026,-81.404237,2021-05-01T10:05:17-0400,medium,2021-05-01 14:05:17+00:00
249,7316024407,https://reading.craigslist.org/ctd/d/paterson-...,reading,https://reading.craigslist.org,18695,2007.0,ram,NaN,diesel,220019,clean,automatic,https://images.craigslist.org/00n0n_jgq4eOvH7I...,2007 Dodge Ram 2500 SLT 4x4 Quad Cab Cummins D...,pa,40.894535,-74.152367,2021-05-02T21:06:09-0400,medium,2021-05-03 01:06:09+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9469,7314341390,https://desmoines.craigslist.org/cto/d/urbanda...,des moines,https://desmoines.craigslist.org,8000,2007.0,toyota,NaN,gas,85285,clean,automatic,https://images.craigslist.org/00K0K_aMoJgOIueB...,Toyota has been owned by non smoker with no pe...,ia,41.629500,-93.723000,2021-04-29T10:50:54-0500,low,2021-04-29 15:50:54+00:00
9521,7304358131,https://vermont.craigslist.org/ctd/d/salem-201...,vermont,https://vermont.craigslist.org,19944,2012.0,ram,NaN,gas,73082,clean,automatic,https://images.craigslist.org/00A0A_bfCaGJ20IX...,2012 RAM 1500 4WD REGULAR CAB SHORT BED 5.7 HE...,vt,42.788204,-71.233728,2021-04-09T16:24:23-0400,medium,2021-04-09 20:24:23+00:00
9573,7309686008,https://louisville.craigslist.org/cto/d/radcli...,louisville,https://louisville.craigslist.org,1600,2005.0,gmc,NaN,gas,52536,clean,automatic,https://images.craigslist.org/01111_99unV6cYER...,GMC Savana PRO AWD cargo van has been driven l...,ky,37.858900,-86.006900,2021-04-20T04:48:30-0400,low,2021-04-20 08:48:30+00:00
9828,7316447901,https://tulsa.craigslist.org/cto/d/tulsa-2017-...,tulsa,https://tulsa.craigslist.org,65000,2017.0,rover,NaN,gas,47000,clean,automatic,https://images.craigslist.org/00s0s_iGpmplDL99...,"2017 Range Rover HSE, supercharged V8, silver ...",ok,36.126200,-95.940800,2021-05-03T16:37:36-0500,high,2021-05-03 21:37:36+00:00
9874,7316458200,https://portland.craigslist.org/mlt/cto/d/port...,portland,https://portland.craigslist.org,18500,1972.0,chevrolet,NaN,gas,75000,clean,automatic,https://images.craigslist.org/00x0x_7FqS8iHJst...,1972 classic Chevrolet pick up custom deluxe ...,or,45.494960,-122.666988,2021-05-03T14:58:34-0700,medium,2021-05-03 21:58:34+00:00

4. Если подробнее изучить значения описания автомобиля, то, возможно, модель автомобиля получится восстановить из описания. Сейчас обработайте пропуски, заполнив незаполненные значения модели автомобиля значением `other`, и сохраните изменения. Обратите внимание, что мы в очередной раз заполняем пропуски не самым популярным значением в выборке.

In [24]:
df.model = df.model.fillna('other')

5. Выведите для обновлённого датафрейма количество пропущенных значений для модели автомобиля.

In [25]:
print("Количество пропущенных значений в model:", df.model.isna().sum())

Количество пропущенных значений в model: 0

### Задача 5. Обработка пропусков в статусе автомобиля

1. Выведите количество значений для статуса автомобиля, включая пропущенные значения. Обратите внимание на количество пропущенных значений.

In [26]:
df.title_status.value_counts(dropna=False)

clean         9397
rebuilt        168
NaN            159
salvage         91
lien            35
missing         16
parts only       2
Name: title_status, dtype: int64

2. Выведите описательные статистики для модели автомобиля.

In [27]:
df.title_status.describe()

count      9709
unique        6
top       clean
freq       9397
Name: title_status, dtype: object

3. Выведите записи, в которых статус автомобиля не заполнен. Посмотрите на данные и подумайте, какую стратегию обработки значений можно применить.

In [28]:
df[df.title_status.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
11,7316540706,https://cincinnati.craigslist.org/ctd/d/fairfi...,cincinnati,https://cincinnati.craigslist.org,4995,2012.0,fiat,500 pop,gas,59242,NaN,manual,https://images.craigslist.org/00Z0Z_jbUmVcYlwR...,"2012 Fiat 500 Pop FOR ONLY $102/mo!59,242 mi. ...",oh,39.297045,-84.563243,2021-05-03T21:03:32-0400,low,2021-05-04 01:03:32+00:00
185,7313570594,https://orangecounty.craigslist.org/ctd/d/coro...,orange county,https://orangecounty.craigslist.org,17900,2013.0,ram,1500 tradesman quad cab,gas,145499,NaN,automatic,https://images.craigslist.org/00H0H_1JFMPCYyW8...,2013 Ram 1500 Tradesman Quad Cab PRICED TO SEL...,ca,33.873436,-117.542806,2021-04-27T15:03:47-0700,medium,2021-04-27 22:03:47+00:00
243,7315211652,https://ocala.craigslist.org/ctd/d/riverview-2...,ocala,https://ocala.craigslist.org,40990,2019.0,toyota,sienna xle,gas,3700,NaN,automatic,https://images.craigslist.org/01111_grKNF8GrXz...,2019 Toyota Sienna - Wheelchair Accessible Han...,fl,27.849760,-82.364950,2021-05-01T06:35:56-0400,high,2021-05-01 10:35:56+00:00
284,7306702976,https://toledo.craigslist.org/ctd/d/chelsea-73...,toledo,https://toledo.craigslist.org,4592,2003.0,chevrolet,avalanche 1500,gas,268691,NaN,automatic,https://images.craigslist.org/00808_1IOMJuA4GL...,$73/mo - 2003 Chevrolet Avalanche 1500 BaseCre...,oh,42.300673,-84.024108,2021-04-14T12:03:01-0400,low,2021-04-14 16:03:01+00:00
310,7307609203,https://roseburg.craigslist.org/ctd/d/eugene-2...,roseburg,https://roseburg.craigslist.org,18450,2017.0,ford,mustang,gas,66049,NaN,automatic,https://images.craigslist.org/00505_4apF36sLbP...,"2017 Ford MUSTANG - $18,450 \tMayberry Motors ...",or,44.058499,-123.106176,2021-04-16T04:06:29-0700,medium,2021-04-16 11:06:29+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,7301707830,https://tricities.craigslist.org/ctd/d/bristol...,tri-cities,https://tricities.craigslist.org,8995,2013.0,honda,odyssey,gas,203112,NaN,automatic,https://images.craigslist.org/00u0u_bawW7HN8xW...,"2013 *Honda* *Odyssey* 5dr EX Van FWD - $8,995...",tn,36.541821,-82.234645,2021-04-04T13:12:27-0400,low,2021-04-04 17:12:27+00:00
9708,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,other,95674,NaN,other,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low,2021-04-28 18:25:32+00:00
9743,7314987181,https://nashville.craigslist.org/ctd/d/nashvil...,nashville,https://nashville.craigslist.org,20900,2014.0,lexus,rx 350,gas,70800,NaN,automatic,https://images.craigslist.org/00Q0Q_cGablAkoYV...,2014 *Lexus* *RX 350* 2014 LEXUS RX 350 SUV 1-...,tn,36.138022,-86.732261,2021-04-30T15:00:48-0500,medium,2021-04-30 20:00:48+00:00
9759,7309717260,https://savannah.craigslist.org/ctd/d/jacksonv...,savannah / hinesville,https://savannah.craigslist.org,11495,2006.0,lexus,gx 470,gas,242000,NaN,automatic,https://images.craigslist.org/00s0s_8xg4gw6aAg...,"2006 *Lexus* *GX 470* 4dr SUV 4WD - $11,495By ...",ga,30.513566,-81.621875,2021-04-20T08:01:49-0400,medium,2021-04-20 12:01:49+00:00
9883,7315557731,https://minneapolis.craigslist.org/csw/ctd/d/d...,minneapolis / st paul,https://minneapolis.craigslist.org,38943,2008.0,ford,f750 super duty - 55ft,diesel,81214,NaN,automatic,https://images.craigslist.org/00y0y_5jr8fQlu7e...,2008 Ford F750 F 750 F-750 Super Duty 55ft 55 ...,mn,45.082884,-94.334760,2021-05-01T18:03:06-0500,high,2021-05-01 23:03:06+00:00

4. Обработайте пропуски, заполнив незаполненные значения статуса автомобиля самым популярным значением, и сохраните изменения. Самое популярное значение передайте не в виде строки, а получите моду.

In [29]:
df.title_status = df.title_status.fillna(df.title_status.mode()[0])
df.title_status.value_counts(dropna = False)

clean         9556
rebuilt        168
salvage         91
lien            35
missing         16
parts only       2
Name: title_status, dtype: int64

5. Выведите для обновлённого датафрейма количество пропущенных значений для статуса автомобиля.

In [30]:
print("Количество пропущенных значений в title_status:", df.title_status.isna().sum())

Количество пропущенных значений в title_status: 0

6. Ещё раз выведите количество полностью заполненных объектов и их процент из всей выборки. После обработки всех пропусков можно переходить к следующему этапу.

In [31]:
missing_values(df)

id                0.0
url               0.0
price_category    0.0
posting_date      0.0
long              0.0
lat               0.0
state             0.0
description       0.0
image_url         0.0
transmission      0.0
title_status      0.0
odometer          0.0
fuel              0.0
model             0.0
manufacturer      0.0
year              0.0
price             0.0
region_url        0.0
region            0.0
date              0.0
dtype: float64

### Задача 6. Преобразование типа данных в годе выпуска автомобиля
1.  Выведите информацию о датафрейме и обратите внимание на типы данных.

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9868 entries, 0 to 9901
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9868 non-null   int64
 1   url             9868 non-null   object
 2   region          9868 non-null   object
 3   region_url      9868 non-null   object
 4   price           9868 non-null   int64
 5   year            9868 non-null   float64
 6   manufacturer    9868 non-null   object
 7   model           9868 non-null   object
 8   fuel            9868 non-null   object
 9   odometer        9868 non-null   int64
 10  title_status    9868 non-null   object
 11  transmission    9868 non-null   object
 12  image_url       9868 non-null   object
 13  description     9868 non-null   object
 14  state           9868 non-null   object
 15  lat             9868 non-null   float64
 16  long            9868 non-null   float64
 17  posting_date    9868 non-null   object
 18  price_category  9868 non-null   object
 19  date            9868 non-null   object
dtypes: float64(3), int64(3), object(14)
memory usage: 1.6+ MB

2. Выведите описательные статистики для года выпуска автомобиля. Обратите внимание на тип данных.

In [33]:
df.year.describe()

count    9868.000000
mean     2010.909708
std         9.705988
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

3. Измените тип данных для года выпуска на более подходящий целочисленный тип и выведите получившийся тип данных только для года выпуска.

In [34]:
df.year = df.year.astype(int)
df.year.dtype

dtype('int32')

### Задача 7. Преобразование типа данных в категориальных переменных

1. Выведите тип данных для типа топлива автомобиля.

In [35]:
df.fuel.dtype

dtype('O')

2. Категориальным переменным можно задавать специальный тип данных `category`. Подробнее об этом можно прочитать в [документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html). Укажите для типа топлива тип данных `category`, сохраните изменения в переменную `series` и выведите её.

In [36]:
series = df.fuel.astype('category')

3. Выведите тип данных для серии. Обратите внимание на структуру вывода.

In [37]:
series.dtype

CategoricalDtype(categories=['diesel', 'electric', 'gas', 'hybrid', 'other'], ordered=False)

4. Выведите первые две категории, используя вывод типа данных выше.

In [38]:
series.dtype.categories.to_list()[:2]

['diesel', 'electric']

### Задача 8. Выбросы в годе выпуска

1. Выведите описательные статистики для года выпуска автомобиля. Обратите внимание на пограничные значения, на квартили.

In [39]:
df.year.describe()

count    9868.000000
mean     2010.909708
std         9.705988
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

2. Выведите границы для нормальных значений года выпуска, используя интерквартильный размах. Воспользуйтесь материалами из видео. Посмотрите, входят ли минимальное и максимальное значения в интервал между полученными границами.

In [40]:
def boundaries(data):
    q25 = data.quantile(0.25)
    q75 = data.quantile(0.75)
    iqr = q75 - q25
    boundaries = (q25 - 1.5 * iqr, q75 + 1.5 * iqr)

    return boundaries

In [41]:
boundaries(df.year)

(1994.5, 2030.5)

3. Посчитайте и выведите количество выбросов в годе выпуска автомобиля.

In [47]:
scopes = boundaries(df.year)
is_outlier = (df['year'] < scopes[0]) | (df['year'] > scopes[1])
is_outlier.sum()

394

4. Посчитайте и выведите долю выбросов в годе выпуска автомобиля.

In [51]:
print (f'доля выбросов в годе выпуска автомобиля: {round (is_outlier.sum()/len(df) * 100, 2)} %')

доля выбросов в годе выпуска автомобиля: 3.99 %

5. Выведите записи, в которых год выпуска попадает в выбросы. Посмотрите на данные и подумайте, могут ли эти выбросы описывать особые значения категории цены или других признаков или действительно являются выбросами.

In [53]:
df[is_outlier]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
13,7317089086,https://seattle.craigslist.org/see/ctd/d/portl...,seattle-tacoma,https://seattle.craigslist.org,14995,1994,ford,e-series van universal by glaval designer luxu...,gas,156925,clean,automatic,https://images.craigslist.org/00r0r_13JUlXZOMl...,"Priced to Sell: $14,9951994 Ford E-Series Van ...",wa,45.391373,-122.613533,2021-05-04T20:22:11-0700,medium,2021-05-05 03:22:11+00:00
21,7312327909,https://madison.craigslist.org/cto/d/madison-1...,madison,https://madison.craigslist.org,89995,1970,other,oldsmobile 442,gas,111111,clean,automatic,https://images.craigslist.org/00S0S_agk7Nol4CO...,1970 Oldsmobile 442 Convertible 442 Indy Pace ...,wi,43.098400,-89.273400,2021-04-25T10:10:43-0500,high,2021-04-25 15:10:43+00:00
57,7314413105,https://inlandempire.craigslist.org/ctd/d/cost...,inland empire,https://inlandempire.craigslist.org,69888,1948,ford,coe,gas,1,clean,automatic,https://images.craigslist.org/00M0M_8jgBCZZuG6...,Awesome Resto-Mod COE Ford Car Hauler. Equippe...,ca,33.680100,-117.908500,2021-04-29T10:49:29-0700,high,2021-04-29 17:49:29+00:00
66,7310077530,https://hudsonvalley.craigslist.org/cto/d/bloo...,hudson valley,https://hudsonvalley.craigslist.org,5500,1990,other,Diahatsu,gas,30000,clean,manual,https://images.craigslist.org/00T0T_a4VRbx40ea...,1991 Daihatsu hijet 5 speed extended cab....im...,ny,41.564400,-74.430400,2021-04-20T18:30:18-0400,low,2021-04-20 22:30:18+00:00
106,7314527175,https://rapidcity.craigslist.org/ctd/d/sherman...,rapid city / west SD,https://rapidcity.craigslist.org,43500,1968,chevrolet,camaro,gas,43320,clean,manual,https://images.craigslist.org/00h0h_2N66LMJBAI...,1968 Chevrolet Camaro Convertible. VIN:124678N...,sd,33.637200,-96.618400,2021-04-29T15:11:01-0600,high,2021-04-29 21:11:01+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9789,7313487583,https://springfield.craigslist.org/cto/d/mount...,springfield,https://springfield.craigslist.org,3500,1974,jeep,cj5,gas,10000,clean,manual,https://images.craigslist.org/00G0G_cdxzaTaVqa...,1974 Jeep cj5 304 v8 4speed manual trans Da...,mo,36.331200,-92.375300,2021-04-27T14:30:28-0500,low,2021-04-27 19:30:28+00:00
9823,7311566144,https://chico.craigslist.org/cto/d/chico-1994-...,chico,https://chico.craigslist.org,16000,1994,ford,f250,gas,32500,clean,automatic,https://images.craigslist.org/01010_343KkgTaHo...,"Up for sale is this 32,000 original mile Ford ...",ca,39.745800,-121.844400,2021-04-23T13:51:20-0700,medium,2021-04-23 20:51:20+00:00
9846,7313676859,https://reno.craigslist.org/ctd/d/sherman-1984...,reno / tahoe,https://reno.craigslist.org,26500,1984,chevrolet,silverado,gas,38751,clean,automatic,https://images.craigslist.org/00r0r_czXfi4UeJF...,"1984 Chevrolet C10 Silverado, short wheelbase ...",ca,33.637200,-96.618400,2021-04-27T19:44:27-0700,high,2021-04-28 02:44:27+00:00
9874,7316458200,https://portland.craigslist.org/mlt/cto/d/port...,portland,https://portland.craigslist.org,18500,1972,chevrolet,other,gas,75000,clean,automatic,https://images.craigslist.org/00x0x_7FqS8iHJst...,1972 classic Chevrolet pick up custom deluxe ...,or,45.494960,-122.666988,2021-05-03T14:58:34-0700,medium,2021-05-03 21:58:34+00:00
9892,7316175335,https://orangecounty.craigslist.org/cto/d/hunt...,orange county,https://orangecounty.craigslist.org,1575,1988,other,1988 Nisan,gas,120000,clean,manual,https://images.craigslist.org/00B0B_5t6BpiGoz9...,Really good running 88 Nissan. Has Sun roof. B...,ca,33.654019,-117.980606,2021-05-03T07:19:18-0700,low,2021-05-03 14:19:18+00:00

6. Выведите количество значений для категории цены для записей, в которых год выпуска автомобиля является выбросом. Описывают ли аномальные значения года выпуска какое-либо из значений цены автомобиля лучше, чем остальные?

In [56]:
df[is_outlier].price_category.value_counts()
# Доли вхождений в каждой из категории сопоставимы. Старые машины бывают как антикварными ценностями, так и металлоломом.
# Сделать явный вывод о влиянии именно года выпуска на цену нельзя.

low       181
medium    135
high       78
Name: price_category, dtype: int64

7. Так как выбросы в годе выпуска находятся среди минимальных значений, заполните те значения, которые являются выбросами, значением нижней границы. Не забудьте учесть, что год должен быть целочисленным значением, входящим в границы нормальных значений.

In [57]:
df.loc[is_outlier, 'year'] = int(scopes[0])

8. Выведите ещё раз описательные статистики для года выпуска автомобиля, чтобы проверить, что теперь все значения года входят в границы нормальных значений.

In [58]:
df.year.describe()

count    9868.000000
mean     2011.658391
std         6.530991
min      1994.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

## Дополнительные задачи

### Задача 9. Загрузка датафрейма с параметрами преобразования

Некоторые преобразования признаков можно сделать ещё в момент загрузки датафрейма из файла.

1. Прочитайте в новый датафрейм файл `data/vehicles_dataset.csv`, выбрав только нужные колонки и применив приведение типов данных. Обратитесь к [документации](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html), чтобы узнать, за что отвечают параметры `usecols`,  `parse_dates` и `dtype`.


Датафрейм должен содержать:
- колонки `price`, `year`, `posting_date`;
- `posting_date` в datatime-формате;
- `price` в вещественном формате;
- `year` в целочисленном формате.

Возможно, вы столкнётесь с ошибкой при считывании года в виде целого числа. Подробнее о том, как бороться с этой ошибкой, можно узнать в документации по `обнуляемому целочисленному типу данных`:
- https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html

*Подсказка:* Pandas может представлять целочисленные данные с возможными отсутствующими значениями, используя [arrays.IntegerArray](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.arrays.IntegerArray.html#pandas.arrays.IntegerArray) или его псевдонимы, которые вы сможете найти в документации.

In [135]:
df2=pd.read_csv('data/vehicles_dataset.csv', usecols=['posting_date', 'year', 'price'], dtype = {'year':'Int64', 'price':'float64'}, parse_dates = ['posting_date'], date_parser = lambda x: pd.to_datetime(x, utc=True))
df2.head(5)

     price  year              posting_date
0  54990.0  2020 2021-04-17 16:30:50+00:00
1  16942.0  2016 2021-05-03 19:40:21+00:00
2  35590.0  2017 2021-04-28 10:52:20+00:00
3  14500.0  2013 2021-04-17 14:08:57+00:00
4  21800.0  2021 2021-05-03 22:32:06+00:00

2. Выведите информацию о датафрейме, чтобы убедиться, что признаки при загрузке преобразовались верно.

In [136]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10050 entries, 0 to 10049
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         10050 non-null  float64
 1   year          10014 non-null  Int64
 2   posting_date  10048 non-null  datetime64[ns, UTC]
dtypes: Int64(1), datetime64[ns, UTC](1), float64(1)
memory usage: 245.5 KB

3. Для первой записи в датафрейме извлеките из `posting_date` и выведите номер месяца.

In [129]:
df2.posting_date[0].month

4